INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AF', 93, 'Afghanistan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AX', -1, 'Åland Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AL', 355, 'Albania');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'DZ', 213, 'Algeria');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AS', 684, 'American Samoa');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AD', 376, 'Andorra');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AO', 244, 'Angola');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AI', 809, 'Anguilla');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AQ', -1, 'Antarctica');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AG', 268, 'Antigua And Barbuda');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AR', 54, 'Argentina');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AM', 374, 'Armenia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AW', 297, 'Aruba');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AU', 61, 'Australia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AT', 43, 'Austria');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AZ', 994, 'Azerbaijan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BS', 242, 'Bahamas');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BH', 973, 'Bahrain');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BD', 880, 'Bangladesh');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BB', 246, 'Barbados');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BY', 375, 'Belarus');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BE', 32, 'Belgium');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BZ', 501, 'Belize');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BJ', 229, 'Benin');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BM', 809, 'Bermuda');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BT', 975, 'Bhutan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BO', 591, 'Bolivia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BA', 387, 'Bosnia And Herzegovina');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BW', 267, 'Botswana');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BV', -1, 'Bouvet Island');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BR', 55, 'Brazil');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'IO', -1, 'British Indian Ocean Territory');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BN', 673, 'Brunei Darussalam');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BG', 359, 'Bulgaria');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BF', 226, 'Burkina Faso');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'BI', 257, 'Burundi');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KH', 855, 'Cambodia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CM', 237, 'Cameroon');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CA', 1, 'Canada');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CV', 238, 'Cape Verde');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KY', 345, 'Cayman Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CF', 236, 'Central African Republic');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TD', 235, 'Chad');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CL', 56, 'Chile');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CN', 86, 'China');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CX', -1, 'Christmas Island');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CC', -1, 'Cocos (keeling) Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CO', 57, 'Colombia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KM', 269, 'Comoros');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CG', 242, 'Congo');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CD', 242, 'Congo, The Democratic Republic Of The');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CK', 682, 'Cook Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CR', 506, 'Costa Rica');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CI', 225, 'CÔte d\'Ivoire');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'HR', 385, 'Croatia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CU', 53, 'Cuba');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CY', 357, 'Cyprus');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CZ', 420, 'Czech Republic');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'DK', 45, 'Denmark');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'DJ', 253, 'Djibouti');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'DM', 767, 'Dominica');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'DO', 809, 'Dominican Republic');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'EC', 593, 'Ecuador');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'EG', 20, 'Egypt');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SV', 503, 'El Salvador');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GQ', 240, 'Equatorial Guinea');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'ER', 291, 'Eritrea');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'EE', 372, 'Estonia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'ET', 251, 'Ethiopia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'FK', 500, 'Falkland Islands (Malvinas)');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'FO', 298, 'Faroe Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'FJ', 679, 'Fiji');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'FI', 358, 'Finland');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'FR', 33, 'France');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GF', 594, 'French Guiana');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PF', 689, 'French Polynesia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TF', -1, 'French Southern Territories');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GA', 241, 'Gabon ');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GM', 220, 'Gambia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GE', 995, 'Georgia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'DE', 49, 'Germany');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GH', 233, 'Ghana');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GI', 350, 'Gibraltar');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GR', 30, 'Greece');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GL', 299, 'Greenland');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GD', 473, 'Grenada');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GP', 596, 'Guadeloupe');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GU', 671, 'Guam');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GT', 502, 'Guatemala');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GN', 224, 'Guinea');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GW', 245, 'Guinea-Bissau');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GY', 592, 'Guyana');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'HT', 509, 'Haiti');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'HM', -1, 'Heard Island And McDonald Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'VA', 39, 'Holy See (Vatican City State)');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'HN', 504, 'Honduras');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'HK', 852, 'Hong Kong');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'HU', 36, 'Hungary');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'IS', 354, 'Iceland');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'IN', 91, 'India');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'ID', 62, 'Indonesia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'IR', 98, 'Iran, Islamic Republic Of');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'IQ', 964, 'Iraq');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'IE', 353, 'Ireland');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'IL', 972, 'Israel');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'IT', 39, 'Italy');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'JM', 876, 'Jamaica');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'JP', 81, 'Japan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'JO', 962, 'Jordan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KZ', 7, 'Kazakhstan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KE', 254, 'Kenya');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KI', 686, 'Kiribati');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KP', 850, 'Korea, Democratic People\'s Republic Of');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KR', 82, 'Korea, Republic Of');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KW', 965, 'Kuwait');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KG', 996, 'Kyrgyzstan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'la', 856, 'Lao People\'s Democratic Republic ');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LV', 371, 'Latvia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LB', 961, 'Lebanon');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LS', 266, 'Lesotho');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LR', 231, 'Liberia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LY', 218, 'Libyan Arab Jamahiriya');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LI', 423, 'Liechtenstein');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LT', 370, 'Lithuania');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LU', 352, 'Luxembourg');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MO', 853, 'Macao');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MK', 389, 'Macedonia, The Former Yugoslav Republic Of');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MG', 261, 'Madagascar');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MW', 265, 'Malawi');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MY', 60, 'Malaysia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MV', 960, 'Maldives');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'ML', 223, 'Mali');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MT', 356, 'Malta');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MH', 692, 'Marshall Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MQ', 596, 'Martinique');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MR', 222, 'Mauritania');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MU', 230, 'Mauritius');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'YT', 269, 'Mayotte');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MX', 52, 'Mexico');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'FM', 691, 'Micronesia, Federated States Of');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MD', 373, 'Moldova, Republic Of');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MC', 33, 'Monaco');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MN', 976, 'Mongolia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MS', 473, 'Montserrat');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MA', 212, 'Morocco');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MZ', 258, 'Mozambique');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MM', 95, 'Myanmar');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NA', 264, 'Namibia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NR', 674, 'Nauru');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NP', 977, 'Nepal');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NL', 31, 'Netherlands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AN', 599, 'Netherlands Antilles');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NC', 687, 'New Caledonia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NZ', 64, 'New Zealand');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NI', 505, 'Nicaragua');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NE', 227, 'Niger');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NG', 234, 'Nigeria');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NU', 683, 'Niue');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NF', -1, 'Norfolk Island');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'MP', 1670, 'Northern Mariana Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'NO', 47, 'Norway');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'OM', 968, 'Oman');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PK', 92, 'Pakistan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PW', 680, 'Palau');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PS', -1, 'Palestinian Territory, Occupied');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PA', 507, 'Panama');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PG', 675, 'Papua New Guinea');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PY', 595, 'Paraguay');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PE', 51, 'Peru');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PH', 63, 'Philippines');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PN', -1, 'Pitcairn');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PL', 48, 'Poland');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PT', 351, 'Portugal');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PR', 1787, 'Puerto Rico');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'QA', 974, 'Qatar');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'RE', 262, 'RÉunion');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'RO', 40, 'Romania');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'RU', 7, 'Russian Federation');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'RW', 250, 'Rwanda');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'sh', 290, 'Saint Helena ');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'KN', 869, 'Saint Kitts And Nevis');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LC', -1, 'Saint Lucia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'PM', 508, 'Saint Pierre And Miquelon');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'VC', -1, 'Saint Vincent And The Grenadines');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'WS', 685, 'Samoa');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SM', 378, 'San Marino');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'ST', 239, 'Sao Tome And Principe');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SA', 966, 'Saudi Arabia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SN', 221, 'Senegal');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CS', 381, 'Serbia And Montenegro');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SC', 248, 'Seychelles');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SL', 232, 'Sierra Leone');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SG', 65, 'Singapore');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SK', 421, 'Slovakia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SI', 386, 'Slovenia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SB', 677, 'Solomon Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SO', 252, 'Somalia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'ZA', 27, 'South Africa');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GS', -1, 'South Georgia And The South Sandwich Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'ES', 34, 'Spain');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'LK', 94, 'Sri Lanka');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SD', 249, 'Sudan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SR', 597, 'Suriname');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SJ', -1, 'Svalbard And Jan Mayen');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SZ', 268, 'Swaziland');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SE', 46, 'Sweden');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'CH', 41, 'Switzerland');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'SY', 963, 'Syrian Arab Republic');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TW', 886, 'Taiwan, Province Of China');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TJ', 7, 'Tajikistan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TZ', 2555, 'Tanzania, United Republic Of');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TH', 66, 'Thailand');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TL', -1, 'Timor-Leste');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TG', 228, 'Togo');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TK', 690, 'Tokelau');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TO', 676, 'Tonga');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TT', 1868, 'Trinidad And Tobago');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TN', 216, 'Tunisia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TR', 90, 'Turkey');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TM', 993, 'Turkmenistan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TC', -1, 'Turks And Caicos Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'TV', 688, 'Tuvalu');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'UG', 256, 'Uganda');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'UA', 380, 'Ukraine');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'AE', 971, 'United Arab Emirates');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'GB', 44, 'United Kingdom');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'US', 1, 'United States');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'UM', -1, 'United States Minor Outlying Islands');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'UY', 598, 'Uruguay');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'UZ', 7, 'Uzbekistan');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'VU', 678, 'Vanuatu');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'VE', 58, 'Venezuela');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'VN', 84, 'Viet Nam');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'VG', 284, 'Virgin Islands, British');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'VI', 1340, 'Virgin Islands, U.S.');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'WF', 681, 'Wallis And Futuna');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'EH', -1, 'Western Sahara');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'YE', 381, 'Yemen');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'ZM', 260, 'Zambia');
INSERT INTO geography.Country VALUES (NEXTVAL('hibernate_sequence'), 'ZW', 263, 'Zimbabwe');
