-- deprecated

INSERT INTO geography_country VALUES (NULL, 'AF', 'Afghanistan', 93);
INSERT INTO geography_country VALUES (NULL, 'AX', 'Åland Islands', -1);
INSERT INTO geography_country VALUES (NULL, 'AL', 'Albania', 355);
INSERT INTO geography_country VALUES (NULL, 'DZ', 'Algeria', 213);
INSERT INTO geography_country VALUES (NULL, 'AS', 'American Samoa', 684);
INSERT INTO geography_country VALUES (NULL, 'AD', 'Andorra', 376);
INSERT INTO geography_country VALUES (NULL, 'AO', 'Angola', 244);
INSERT INTO geography_country VALUES (NULL, 'AI', 'Anguilla', 809);
INSERT INTO geography_country VALUES (NULL, 'AQ', 'Antarctica', -1);
INSERT INTO geography_country VALUES (NULL, 'AG', 'Antigua And Barbuda', 268);
INSERT INTO geography_country VALUES (NULL, 'AR', 'Argentina', 54);
INSERT INTO geography_country VALUES (NULL, 'AM', 'Armenia', 374);
INSERT INTO geography_country VALUES (NULL, 'AW', 'Aruba', 297);
INSERT INTO geography_country VALUES (NULL, 'AU', 'Australia', 61);
INSERT INTO geography_country VALUES (NULL, 'AT', 'Austria', 43);
INSERT INTO geography_country VALUES (NULL, 'AZ', 'Azerbaijan', 994);
INSERT INTO geography_country VALUES (NULL, 'BS', 'Bahamas', 242);
INSERT INTO geography_country VALUES (NULL, 'BH', 'Bahrain', 973);
INSERT INTO geography_country VALUES (NULL, 'BD', 'Bangladesh', 880);
INSERT INTO geography_country VALUES (NULL, 'BB', 'Barbados', 246);
INSERT INTO geography_country VALUES (NULL, 'BY', 'Belarus', 375);
INSERT INTO geography_country VALUES (NULL, 'BE', 'Belgium', 32);
INSERT INTO geography_country VALUES (NULL, 'BZ', 'Belize', 501);
INSERT INTO geography_country VALUES (NULL, 'BJ', 'Benin', 229);
INSERT INTO geography_country VALUES (NULL, 'BM', 'Bermuda', 809);
INSERT INTO geography_country VALUES (NULL, 'BT', 'Bhutan', 975);
INSERT INTO geography_country VALUES (NULL, 'BO', 'Bolivia', 591);
INSERT INTO geography_country VALUES (NULL, 'BA', 'Bosnia And Herzegovina', 387);
INSERT INTO geography_country VALUES (NULL, 'BW', 'Botswana', 267);
INSERT INTO geography_country VALUES (NULL, 'BV', 'Bouvet Island', -1);
INSERT INTO geography_country VALUES (NULL, 'BR', 'Brazil', 55);
INSERT INTO geography_country VALUES (NULL, 'IO', 'British Indian Ocean Territory', -1);
INSERT INTO geography_country VALUES (NULL, 'BN', 'Brunei Darussalam', 673);
INSERT INTO geography_country VALUES (NULL, 'BG', 'Bulgaria', 359);
INSERT INTO geography_country VALUES (NULL, 'BF', 'Burkina Faso', 226);
INSERT INTO geography_country VALUES (NULL, 'BI', 'Burundi', 257);
INSERT INTO geography_country VALUES (NULL, 'KH', 'Cambodia', 855);
INSERT INTO geography_country VALUES (NULL, 'CM', 'Cameroon', 237);
INSERT INTO geography_country VALUES (NULL, 'CA', 'Canada', 1);
INSERT INTO geography_country VALUES (NULL, 'CV', 'Cape Verde', 238);
INSERT INTO geography_country VALUES (NULL, 'KY', 'Cayman Islands', 345);
INSERT INTO geography_country VALUES (NULL, 'CF', 'Central African Republic', 236);
INSERT INTO geography_country VALUES (NULL, 'TD', 'Chad', 235);
INSERT INTO geography_country VALUES (NULL, 'CL', 'Chile', 56);
INSERT INTO geography_country VALUES (NULL, 'CN', 'China', 86);
INSERT INTO geography_country VALUES (NULL, 'CX', 'Christmas Island', -1);
INSERT INTO geography_country VALUES (NULL, 'CC', 'Cocos (keeling) Islands', -1);
INSERT INTO geography_country VALUES (NULL, 'CO', 'Colombia', 57);
INSERT INTO geography_country VALUES (NULL, 'KM', 'Comoros', 269);
INSERT INTO geography_country VALUES (NULL, 'CG', 'Congo', 242);
INSERT INTO geography_country VALUES (NULL, 'CD', 'Congo, The Democratic Republic Of The', 242);
INSERT INTO geography_country VALUES (NULL, 'CK', 'Cook Islands', 682);
INSERT INTO geography_country VALUES (NULL, 'CR', 'Costa Rica', 506);
INSERT INTO geography_country VALUES (NULL, 'CI', 'CÔte d\'Ivoire', 225);
INSERT INTO geography_country VALUES (NULL, 'HR', 'Croatia', 385);
INSERT INTO geography_country VALUES (NULL, 'CU', 'Cuba', 53);
INSERT INTO geography_country VALUES (NULL, 'CY', 'Cyprus', 357);
INSERT INTO geography_country VALUES (NULL, 'CZ', 'Czech Republic', 420);
INSERT INTO geography_country VALUES (NULL, 'DK', 'Denmark', 45);
INSERT INTO geography_country VALUES (NULL, 'DJ', 'Djibouti', 253);
INSERT INTO geography_country VALUES (NULL, 'DM', 'Dominica', 767);
INSERT INTO geography_country VALUES (NULL, 'DO', 'Dominican Republic', 809);
INSERT INTO geography_country VALUES (NULL, 'EC', 'Ecuador', 593);
INSERT INTO geography_country VALUES (NULL, 'EG', 'Egypt', 20);
INSERT INTO geography_country VALUES (NULL, 'SV', 'El Salvador', 503);
INSERT INTO geography_country VALUES (NULL, 'GQ', 'Equatorial Guinea', 240);
INSERT INTO geography_country VALUES (NULL, 'ER', 'Eritrea', 291);
INSERT INTO geography_country VALUES (NULL, 'EE', 'Estonia', 372);
INSERT INTO geography_country VALUES (NULL, 'ET', 'Ethiopia', 251);
INSERT INTO geography_country VALUES (NULL, 'FK', 'Falkland Islands (Malvinas)', 500);
INSERT INTO geography_country VALUES (NULL, 'FO', 'Faroe Islands', 298);
INSERT INTO geography_country VALUES (NULL, 'FJ', 'Fiji', 679);
INSERT INTO geography_country VALUES (NULL, 'FI', 'Finland', 358);
INSERT INTO geography_country VALUES (NULL, 'FR', 'France', 33);
INSERT INTO geography_country VALUES (NULL, 'GF', 'French Guiana', 594);
INSERT INTO geography_country VALUES (NULL, 'PF', 'French Polynesia', 689);
INSERT INTO geography_country VALUES (NULL, 'TF', 'French Southern Territories', -1);
INSERT INTO geography_country VALUES (NULL, 'GA', 'Gabon ', 241);
INSERT INTO geography_country VALUES (NULL, 'GM', 'Gambia', 220);
INSERT INTO geography_country VALUES (NULL, 'GE', 'Georgia', 995);
INSERT INTO geography_country VALUES (NULL, 'DE', 'Germany', 49);
INSERT INTO geography_country VALUES (NULL, 'GH', 'Ghana', 233);
INSERT INTO geography_country VALUES (NULL, 'GI', 'Gibraltar', 350);
INSERT INTO geography_country VALUES (NULL, 'GR', 'Greece', 30);
INSERT INTO geography_country VALUES (NULL, 'GL', 'Greenland', 299);
INSERT INTO geography_country VALUES (NULL, 'GD', 'Grenada', 473);
INSERT INTO geography_country VALUES (NULL, 'GP', 'Guadeloupe', 596);
INSERT INTO geography_country VALUES (NULL, 'GU', 'Guam', 671);
INSERT INTO geography_country VALUES (NULL, 'GT', 'Guatemala', 502);
INSERT INTO geography_country VALUES (NULL, 'GN', 'Guinea', 224);
INSERT INTO geography_country VALUES (NULL, 'GW', 'Guinea-Bissau', 245);
INSERT INTO geography_country VALUES (NULL, 'GY', 'Guyana', 592);
INSERT INTO geography_country VALUES (NULL, 'HT', 'Haiti', 509);
INSERT INTO geography_country VALUES (NULL, 'HM', 'Heard Island And McDonald Islands', -1);
INSERT INTO geography_country VALUES (NULL, 'VA', 'Holy See (Vatican City State)', 39);
INSERT INTO geography_country VALUES (NULL, 'HN', 'Honduras', 504);
INSERT INTO geography_country VALUES (NULL, 'HK', 'Hong Kong', 852);
INSERT INTO geography_country VALUES (NULL, 'HU', 'Hungary', 36);
INSERT INTO geography_country VALUES (NULL, 'IS', 'Iceland', 354);
INSERT INTO geography_country VALUES (NULL, 'IN', 'India', 91);
INSERT INTO geography_country VALUES (NULL, 'ID', 'Indonesia', 62);
INSERT INTO geography_country VALUES (NULL, 'IR', 'Iran, Islamic Republic Of', 98);
INSERT INTO geography_country VALUES (NULL, 'IQ', 'Iraq', 964);
INSERT INTO geography_country VALUES (NULL, 'IE', 'Ireland', 353);
INSERT INTO geography_country VALUES (NULL, 'IL', 'Israel', 972);
INSERT INTO geography_country VALUES (NULL, 'IT', 'Italy', 39);
INSERT INTO geography_country VALUES (NULL, 'JM', 'Jamaica', 876);
INSERT INTO geography_country VALUES (NULL, 'JP', 'Japan', 81);
INSERT INTO geography_country VALUES (NULL, 'JO', 'Jordan', 962);
INSERT INTO geography_country VALUES (NULL, 'KZ', 'Kazakhstan', 7);
INSERT INTO geography_country VALUES (NULL, 'KE', 'Kenya', 254);
INSERT INTO geography_country VALUES (NULL, 'KI', 'Kiribati', 686);
INSERT INTO geography_country VALUES (NULL, 'KP', 'Korea, Democratic People\'s Republic Of', 850);
INSERT INTO geography_country VALUES (NULL, 'KR', 'Korea, Republic Of', 82);
INSERT INTO geography_country VALUES (NULL, 'KW', 'Kuwait', 965);
INSERT INTO geography_country VALUES (NULL, 'KG', 'Kyrgyzstan', 996);
INSERT INTO geography_country VALUES (NULL, 'la', 856, 'Lao People\'s Democratic Republic ');
INSERT INTO geography_country VALUES (NULL, 'LV', 'Latvia', 371);
INSERT INTO geography_country VALUES (NULL, 'LB', 'Lebanon', 961);
INSERT INTO geography_country VALUES (NULL, 'LS', 'Lesotho', 266);
INSERT INTO geography_country VALUES (NULL, 'LR', 'Liberia', 231);
INSERT INTO geography_country VALUES (NULL, 'LY', 'Libyan Arab Jamahiriya', 218);
INSERT INTO geography_country VALUES (NULL, 'LI', 'Liechtenstein', 423);
INSERT INTO geography_country VALUES (NULL, 'LT', 'Lithuania', 370);
INSERT INTO geography_country VALUES (NULL, 'LU', 'Luxembourg', 352);
INSERT INTO geography_country VALUES (NULL, 'MO', 'Macao', 853);
INSERT INTO geography_country VALUES (NULL, 'MK', 'Macedonia, The Former Yugoslav Republic Of', 389);
INSERT INTO geography_country VALUES (NULL, 'MG', 'Madagascar', 261);
INSERT INTO geography_country VALUES (NULL, 'MW', 'Malawi', 265);
INSERT INTO geography_country VALUES (NULL, 'MY', 'Malaysia', 60);
INSERT INTO geography_country VALUES (NULL, 'MV', 'Maldives', 960);
INSERT INTO geography_country VALUES (NULL, 'ML', 'Mali', 223);
INSERT INTO geography_country VALUES (NULL, 'MT', 'Malta', 356);
INSERT INTO geography_country VALUES (NULL, 'MH', 'Marshall Islands', 692);
INSERT INTO geography_country VALUES (NULL, 'MQ', 'Martinique', 596);
INSERT INTO geography_country VALUES (NULL, 'MR', 'Mauritania', 222);
INSERT INTO geography_country VALUES (NULL, 'MU', 'Mauritius', 230);
INSERT INTO geography_country VALUES (NULL, 'YT', 'Mayotte', 269);
INSERT INTO geography_country VALUES (NULL, 'MX', 'Mexico', 52);
INSERT INTO geography_country VALUES (NULL, 'FM', 'Micronesia, Federated States Of', 691);
INSERT INTO geography_country VALUES (NULL, 'MD', 'Moldova, Republic Of', 373);
INSERT INTO geography_country VALUES (NULL, 'MC', 'Monaco', 33);
INSERT INTO geography_country VALUES (NULL, 'MN', 'Mongolia', 976);
INSERT INTO geography_country VALUES (NULL, 'MS', 'Montserrat', 473);
INSERT INTO geography_country VALUES (NULL, 'MA', 'Morocco', 212);
INSERT INTO geography_country VALUES (NULL, 'MZ', 'Mozambique', 258);
INSERT INTO geography_country VALUES (NULL, 'MM', 'Myanmar', 95);
INSERT INTO geography_country VALUES (NULL, 'NA', 'Namibia', 264);
INSERT INTO geography_country VALUES (NULL, 'NR', 'Nauru', 674);
INSERT INTO geography_country VALUES (NULL, 'NP', 'Nepal', 977);
INSERT INTO geography_country VALUES (NULL, 'NL', 'Netherlands', 31);
INSERT INTO geography_country VALUES (NULL, 'AN', 'Netherlands Antilles', 599);
INSERT INTO geography_country VALUES (NULL, 'NC', 'New Caledonia', 687);
INSERT INTO geography_country VALUES (NULL, 'NZ', 'New Zealand', 64);
INSERT INTO geography_country VALUES (NULL, 'NI', 'Nicaragua', 505);
INSERT INTO geography_country VALUES (NULL, 'NE', 'Niger', 227);
INSERT INTO geography_country VALUES (NULL, 'NG', 'Nigeria', 234);
INSERT INTO geography_country VALUES (NULL, 'NU', 'Niue', 683);
INSERT INTO geography_country VALUES (NULL, 'NF', 'Norfolk Island', -1);
INSERT INTO geography_country VALUES (NULL, 'MP', 'Northern Mariana Islands', 1670);
INSERT INTO geography_country VALUES (NULL, 'NO', 'Norway', 47);
INSERT INTO geography_country VALUES (NULL, 'OM', 'Oman', 968);
INSERT INTO geography_country VALUES (NULL, 'PK', 'Pakistan', 92);
INSERT INTO geography_country VALUES (NULL, 'PW', 'Palau', 680);
INSERT INTO geography_country VALUES (NULL, 'PS', 'Palestinian Territory, Occupied', -1);
INSERT INTO geography_country VALUES (NULL, 'PA', 'Panama', 507);
INSERT INTO geography_country VALUES (NULL, 'PG', 'Papua New Guinea', 675);
INSERT INTO geography_country VALUES (NULL, 'PY', 'Paraguay', 595);
INSERT INTO geography_country VALUES (NULL, 'PE', 'Peru', 51);
INSERT INTO geography_country VALUES (NULL, 'PH', 'Philippines', 63);
INSERT INTO geography_country VALUES (NULL, 'PN', 'Pitcairn', -1);
INSERT INTO geography_country VALUES (NULL, 'PL', 'Poland', 48);
INSERT INTO geography_country VALUES (NULL, 'PT', 'Portugal', 351);
INSERT INTO geography_country VALUES (NULL, 'PR', 'Puerto Rico', 1787);
INSERT INTO geography_country VALUES (NULL, 'QA', 'Qatar', 974);
INSERT INTO geography_country VALUES (NULL, 'RE', 'RÉunion', 262);
INSERT INTO geography_country VALUES (NULL, 'RO', 'Romania', 40);
INSERT INTO geography_country VALUES (NULL, 'RU', 'Russian Federation', 7);
INSERT INTO geography_country VALUES (NULL, 'RW', 'Rwanda', 250);
INSERT INTO geography_country VALUES (NULL, 'sh', 290, 'Saint Helena ');
INSERT INTO geography_country VALUES (NULL, 'KN', 'Saint Kitts And Nevis', 869);
INSERT INTO geography_country VALUES (NULL, 'LC', 'Saint Lucia', -1);
INSERT INTO geography_country VALUES (NULL, 'PM', 'Saint Pierre And Miquelon', 508);
INSERT INTO geography_country VALUES (NULL, 'VC', 'Saint Vincent And The Grenadines', -1);
INSERT INTO geography_country VALUES (NULL, 'WS', 'Samoa', 685);
INSERT INTO geography_country VALUES (NULL, 'SM', 'San Marino', 378);
INSERT INTO geography_country VALUES (NULL, 'ST', 'Sao Tome And Principe', 239);
INSERT INTO geography_country VALUES (NULL, 'SA', 'Saudi Arabia', 966);
INSERT INTO geography_country VALUES (NULL, 'SN', 'Senegal', 221);
INSERT INTO geography_country VALUES (NULL, 'CS', 'Serbia And Montenegro', 381);
INSERT INTO geography_country VALUES (NULL, 'SC', 'Seychelles', 248);
INSERT INTO geography_country VALUES (NULL, 'SL', 'Sierra Leone', 232);
INSERT INTO geography_country VALUES (NULL, 'SG', 'Singapore', 65);
INSERT INTO geography_country VALUES (NULL, 'SK', 'Slovakia', 421);
INSERT INTO geography_country VALUES (NULL, 'SI', 'Slovenia', 386);
INSERT INTO geography_country VALUES (NULL, 'SB', 'Solomon Islands', 677);
INSERT INTO geography_country VALUES (NULL, 'SO', 'Somalia', 252);
INSERT INTO geography_country VALUES (NULL, 'ZA', 'South Africa', 27);
INSERT INTO geography_country VALUES (NULL, 'GS', 'South Georgia And The South Sandwich Islands', -1);
INSERT INTO geography_country VALUES (NULL, 'ES', 'Spain', 34);
INSERT INTO geography_country VALUES (NULL, 'LK', 'Sri Lanka', 94);
INSERT INTO geography_country VALUES (NULL, 'SD', 'Sudan', 249);
INSERT INTO geography_country VALUES (NULL, 'SR', 'Suriname', 597);
INSERT INTO geography_country VALUES (NULL, 'SJ', 'Svalbard And Jan Mayen', -1);
INSERT INTO geography_country VALUES (NULL, 'SZ', 'Swaziland', 268);
INSERT INTO geography_country VALUES (NULL, 'SE', 'Sweden', 46);
INSERT INTO geography_country VALUES (NULL, 'CH', 'Switzerland', 41);
INSERT INTO geography_country VALUES (NULL, 'SY', 'Syrian Arab Republic', 963);
INSERT INTO geography_country VALUES (NULL, 'TW', 'Taiwan, Province Of China', 886);
INSERT INTO geography_country VALUES (NULL, 'TJ', 'Tajikistan', 7);
INSERT INTO geography_country VALUES (NULL, 'TZ', 'Tanzania, United Republic Of', 2555);
INSERT INTO geography_country VALUES (NULL, 'TH', 'Thailand', 66);
INSERT INTO geography_country VALUES (NULL, 'TL', 'Timor-Leste', -1);
INSERT INTO geography_country VALUES (NULL, 'TG', 'Togo', 228);
INSERT INTO geography_country VALUES (NULL, 'TK', 'Tokelau', 690);
INSERT INTO geography_country VALUES (NULL, 'TO', 'Tonga', 676);
INSERT INTO geography_country VALUES (NULL, 'TT', 'Trinidad And Tobago', 1868);
INSERT INTO geography_country VALUES (NULL, 'TN', 'Tunisia', 216);
INSERT INTO geography_country VALUES (NULL, 'TR', 'Turkey', 90);
INSERT INTO geography_country VALUES (NULL, 'TM', 'Turkmenistan', 993);
INSERT INTO geography_country VALUES (NULL, 'TC', 'Turks And Caicos Islands', -1);
INSERT INTO geography_country VALUES (NULL, 'TV', 'Tuvalu', 688);
INSERT INTO geography_country VALUES (NULL, 'UG', 'Uganda', 256);
INSERT INTO geography_country VALUES (NULL, 'UA', 'Ukraine', 380);
INSERT INTO geography_country VALUES (NULL, 'AE', 'United Arab Emirates', 971);
INSERT INTO geography_country VALUES (NULL, 'GB', 'United Kingdom', 44);
INSERT INTO geography_country VALUES (NULL, 'US', 'United States', 1);
INSERT INTO geography_country VALUES (NULL, 'UM', 'United States Minor Outlying Islands', -1);
INSERT INTO geography_country VALUES (NULL, 'UY', 'Uruguay', 598);
INSERT INTO geography_country VALUES (NULL, 'UZ', 'Uzbekistan', 7);
INSERT INTO geography_country VALUES (NULL, 'VU', 'Vanuatu', 678);
INSERT INTO geography_country VALUES (NULL, 'VE', 'Venezuela', 58);
INSERT INTO geography_country VALUES (NULL, 'VN', 'Viet Nam', 84);
INSERT INTO geography_country VALUES (NULL, 'VG', 'Virgin Islands, British', 284);
INSERT INTO geography_country VALUES (NULL, 'VI', 'Virgin Islands, U.S.', 1340);
INSERT INTO geography_country VALUES (NULL, 'WF', 'Wallis And Futuna', 681);
INSERT INTO geography_country VALUES (NULL, 'EH', 'Western Sahara', -1);
INSERT INTO geography_country VALUES (NULL, 'YE', 'Yemen', 381);
INSERT INTO geography_country VALUES (NULL, 'ZM', 'Zambia', 260);
INSERT INTO geography_country VALUES (NULL, 'ZW', 'Zimbabwe', 263);
