package biz.janux.payment;


/**
 * 
 * Represents the response of a {@link Settlement} 
 * 
 * @author Nilesh
 * @author albertobuffagni@gmail.com
 * 
 */
public interface SettlementResponse extends TransactionResponse {

	/**
	 * The record format designation for all messages defined in this specification is "K".
	 */
	public String getRecordFormat();
	public void setRecordFormat(String recordFormat);

	/**
	 * The data capture system allows the user the option of settling single or multiple batches 
	 * per connection. 
	 * 
	 * Table4.2  provides a listing of currently supported Application Types. 
	 * 
	 * Please reference EIS 1052 for a detailed description of the communication protocol differences 
	 * dictated by each application type option.
	 * 
	 * Table 4.2  Application type
	 * Application type Description
	 * 1 Single batch per connection
	 * 3 Multiple batches per connection
	 */
	public String getApplicationType();
	public void setApplicationType(String applicationType);

	/**
	 * The X.25 Routing Identifier is utilized for the routing of the settlement packets though the 
	 * Vital system. This character is defined as a "Z".
	 */
	public String getRoutingID();
	public void setRoutingID(String routingID);

	/**
	 * The Record Type is a 5-character field utilized to define the characteristics of a settlement 
	 * record being submitted for processing on the Vital system. The first byte of the Record Type 
	 * field designates the general classification of the settlement record. Table4.25  provides a 
	 * listing of current record types.
	 * Table 4.25  Record type
	 * 
	 * Value Record type
	 * H Header Record
	 * P Parameter Record
	 * D Detail Record
	 * L Line Item Detail Record (Commercial Card)
	 * M Trip-Leg Detail Record (Commercial Card)
	 * T Trailer Record
	 * R Trailer Response Record
	 */
	public String getRecordType();
	public void setRecordType(String recordType);

	/**
	 * This 9-character numeric field contains a batch record count calculated by the point of sale 
	 * device. 
	 * 
	 * This field is supplied in the Batch Trailer record and must contain the total number of 
	 * records in the batch - including Header, Parameter, Detail(s), and Trailer records. Blocking 
	 * has no effect upon the record count. The total record count must be right-justified and zero-
	 * filled to 9 positions.
	 * 
	 * When this field is returned by the host in a batch response message, it will reflect the total 
	 * number of records having been received by the host. In the case of a GB (Good Batch) 
	 * response, the value returned should match the value supplied. However, in the case of an RB 
	 * (Rejected Batch) response, the batch record count will reflect the total number of records 
	 * received until the point of failure. Hence, the returned record count will reveal the sequential 
	 * number of the record responsible for causing a rejected batch condition.
	 */
	public String getBatchRecordCount();
	public void setBatchRecordCount(String batchRecordCount);

	/**
	 * This field contains the net deposit generated by the terminal. The net deposit total is 
	 * generated by adding the settlement amounts of all Detail transaction records and subtracting 
	 * credit or refund amounts from it. Void transaction amounts are not factored into this amount. 
	 * The field entry must be right-justified and zero-filled to 16 positions. This field is represented 
	 * as an 'absolute value'.
	 */
	public String getBatchNetDeposit();
	public void setBatchNetDeposit(String batchNetDeposit);

	/**
	 * This field contains the 2-character response code returned by the host indicating the status of
	 * the batch settlement attempt. 
	 * 
	 * Table4.4  provides a summary of the responses returned by the
	 * Visa data capture host.
	 * 
	 * Table 4.4  Batch response code.
	 * Code Description
	 * GB Good Batch
	 * QD Duplicate Batch
	 * RB Rejected Batch
	 */
	public String getBatchResponseCode();
	public void setBatchResponseCode(String batchResponseCode);

	/**
	 * This field contains a 3-character numeric batch sequence number generated by the POS 
	 * device. The batch number must be a number within the range of 001-999. If the POS device 
	 * is automatically incrementing the batch number, it should automatically advance the number 
	 * from 999 to 001 (000 is invalid). Batch Numbers must not be reused or repeated within five 
	 * consecutive days. This field should be configurable as a parameter.
	 */
	public String getBatchNumber();
	public void setBatchNumber(String batchNumber);

	/**
	 * This 9 character field will contain the text " _ACCEPTED" when a settlement batch has been
	 * successfully received by the host; however, the POS device should examine only the Batch 
	 * Response code to determine the status of particular batch status.
	 */
	public String getBatchResponseText();
	public void setBatchResponseText(String batchResponseText);

	/**
	 * This 4-character numeric field contains the transmission date of the settlement batch. The 
	 * transmission date must be provided in MMDD format.
	 * 
	 * It is not persistent
	 */
	public String getBatchTransmissionDate();
	public void setBatchTransmissionDate(String batchTransmissionDate);

	/**
	 * This 1-character field defines the nature of a rejected batch. Table4.12  provides a listing of 
	 * currently defined error types.
	 * 
	 * Table 4.12  Error type
	 * Value Description
	 * B Blocked Terminal
	 * C Card Type Error
	 * D Device Error
	 * E Error in Batch
	 * P Vital Residency Requirement Error
	 * S Sequence Error
	 * T Transmission Error
	 * U Unknown Error
	 * V Routing Error
	 * 
	 * It is not persistent
	 */
	public String getErrorType();
	public void setErrorType(String errorType);

	/**
	 * This 4-character numeric field contains the sequential number of the data record which 
	 * caused the rejected batch state. For example, a rejected Header Record would be "0001" and a 
	 * rejected Parameter Record would be "0002".
	 * 
	 * It is not persistent
	 */
	public String getErrorRecordSeq();
	public void setErrorRecordSeq(String errorRecordSeq);

	/**
	 * This 1-character field defines the data record which generated the rejected batch response 
	 * message. Table4.11  provides a listing of currently defined error record types.
	 * 
	 * Table 4.11  Error record type
	 * Value Description
	 * H Header Record 
	 * P Parameter Record
	 * D Detail Record
	 * L Line Item Detail Records
	 * T Trailer Record
	 * K Hierarchy
	 * 
	 * It is not persistent
	 */
	public String getErrorRecordType();
	public void setErrorRecordType(String errorRecordType);

	/**
	 * This 2-character numeric field contains the sequential field number within the data record 
	 * which generated the rejected batch response message.
	 * 
	 * It is not persistent
	 */
	public String getErrorDataFieldNum();
	public void setErrorDataFieldNum(String errorDataFieldNum);

	/**
	 * This 32-character field contains the error data contained within the field which generated the 
	 * rejected batch response message. This information can be useful in identifying and correcting 
	 * the rejected batch condition.
	 * 
	 * It is not persistent
	 */
	public String getErrorData();
	public void setErrorData(String errorData);
}
