package biz.janux.payment;

import java.util.List;

import biz.janux.payment.MerchantAccount;

/**
 * Represents a Settlement Transaction
 * 
 * It is a batch that groups a collection of applied payments {@link SettlementItem} 
 * for a {@link MerchantAccount} 
 * 
 * @author Nilesh
 * @author albertobuffagni@gmail.com 
 * 
 */
public interface Settlement extends Transaction<SettlementResponse> {

	public List<SettlementItem> getSettlementItems();
	public void setSettlementItems(List<SettlementItem> settlementItems);
	
	/**
	 * This field contains a 3-character numeric batch sequence number generated by the POS 
	 * device. The batch number must be a number within the range of 001-999. If the POS device
	 * is automatically incrementing the batch number, it should automatically advance the number 
	 * from 999 to 001 (000 is invalid). Batch Numbers must not be reused or repeated within five 
	 * consecutive days. This field should be configurable as a parameter.
	 */
	public int getBatchNumber();
	public void setBatchNumber(int batchNumber);
	
	public boolean isEnabled();
	public void setEnabled(boolean enabled);
	
	
}
